### ISSUE TITLE
Possibility to extract chapters individually?

### ISSUE THREAD

**Issue by rafael1mc** [kevinboone/epub2txt2#36] opened 2024-12-14 02:29 UTC
Is it possible to either extract chapters individually, or at least to make the output have clear chapter separation?

**Comment by kevinboone** [comment] 2024-12-14 15:12
EPUB doesn't have a clear concept of 'chapter' but it would be possible, in principle, to insert some delimiter between the parsing of each XHTML file in the spine. There's a reasonably strong convention that each XHTML file corresponds to a chapter, although things like title pages and dedications and such-like often get their own spine entry (XHTML file) as well.

With a delimiter between each 'chapter', you could redirect the output of epub2txt to a file, and then use something like csplit to break the file up at the delimiters. 

It wouldn't be splitting on chapters, exactly, but I suspect it would be pretty close for most books. 

Implementing anything more sophisticated than this would, I suspect, be difficult, and would bloat epub2txt more than I feel comfortable with.

**Comment by rafael1mc** [comment] 2024-12-14 23:02
Yeah, I had the same though about handling different cases becoming a lot of bloat.

I'm working on an [ePUB TTS](https://github.com/rafael1mc/epub-tts) and after posting this question, I ended up finding another tool that parses the file into sections - which I assume to be what you mentioned.

Considering how simple my project is, the results seem quite alright with this approach.

Anyways, thanks for taking the time to respond.

**Comment by kevinboone** [comment] 2024-12-15 11:45
I'm assuming that this change is no longer required; closing the issue.

**Closed by kevinboone** 2024-12-15 11:45 UTC

**Comment by teamcoltra** [comment] 2024-12-18 09:17
Hey @kevinboone I would still really like this feature. In the past I had "hacked" the output to look for the text "Chapter 1" (Regex'd with some alternatives)  and failing that head -n X which was the average number of lines to get to the first chapter. Pulling chapter information would be great for my needs. 

I'm not working on that project again right now, however, it would be convenient. Maybe it can be on the road map but low priority?

**Comment by kevinboone** [comment] 2024-12-18 14:21
What kind of separator would be useful? It could just a line of text, or it could include the spine entry. Unfortunately, because so many EPUBs are created by automation, the spine entry is often just gibberish. If text, it would need to be something that isn't likely to appear in a document. Suggestions welcome.

It would be nice if there could be a separator that included the title from the table of contents (if there is one). But this would require another stage of XML parsing, which would double the size of the utility. The problem isn't the amount of work (although it's probably a few hours of work), but my attempts to keep epub2txt small and manageable.

**Comment by rafael1mc** [comment] 2024-12-18 15:33
> I'm assuming that this change is no longer required

Yes, no longer required, for me at least.

<hr>

I got the notification, so my two cents would be to add parameter(s), eg:
```
$ epub2txt --section-sepator=----foo-bar----
```

And it would add this user-defined separator to the output.

**Comment by kevinboone** [comment] 2024-12-19 08:56
Since there seems to be some small interest, I implemented '-s, --separator=text' so you can write an arbitrary line of text before outputting each spine item. It only adds about six lines of code to the program. How useful it will be in practice, I'm not sure. Still, it wasn't a big deal to add.
